export const members = [
    { index: 1, "name": "Anoushka Paul", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 2, "name": "Arpitha R", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 3, "name": "Ganeshayya Shidaganti", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 4, "name": "Hitansh Jain", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 5, "name": "Hrishikesh Chandi", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 6, "name": "Kirti Sharma", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 7, "name": "Kushal L", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 8, "name": "Mayur Shetty", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 9, "name": "Meeradevi A K", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 10, "name": "Pranav K", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 11, "name": "Ranjita Nayak", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 12, "name": "Roopin Nayak", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 13, "name": "Sagar S R", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 14, "name": "Saikiran K Shet", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 15, "name": "Saksham Yadav", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 16, "name": "Samrudh P", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 17, "name": "Sandesh Huli", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 18, "name": "Shashidhar Gayakawad", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 19, "name": "Shreya Mahesh", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 20, "name": "Shrihari Joshi", "role": "Chapter", "image": '/user.jpg', },
    { index: 21, "name": "Shubham Khatri", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 22, "name": "Soham Dave", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 23, "name": "Sowmya Bj", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 24, "name": "Subham Choudhary", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 25, "name": "Suhas Vankadari", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 26, "name": "Swanand Gadwe", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 27, "name": "Utsav S R", "role": "Chapter Member", "image": '/user.jpg', },
    { index: 28, "name": "Varsha M", "role": "Chapter Member", "image": '/user.jpg', }
];
