export const members = [
    { "name": "Anoushka Paul", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Arpitha R", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Ganeshayya Shidaganti", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Hitansh Jain", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Hrishikesh Chandi", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Kirti Sharma", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Kushal L", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Mayur Shetty", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Meeradevi A K", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Pranav K", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Ranjita Nayak", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Roopin Nayak", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Sagar S R", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Saikiran K Shet", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Saksham Yadav", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Samrudh P", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Sandesh Huli", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Shashidhar Gayakawad", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Shreya Mahesh", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Shrihari Joshi", "role": "Chapter", "image": '/background.jpg', },
    { "name": "Shubham Khatri", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Soham Dave", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Sowmya Bj", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Subham Choudhary", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Suhas Vankadari", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Swanand Gadwe", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Utsav S R", "role": "Chapter Member", "image": '/background.jpg', },
    { "name": "Varsha M", "role": "Chapter Member", "image": '/background.jpg', }
]
